name: Build
on:
  push:
  workflow_dispatch:
jobs:
  test:
    uses: spagoveanu/test1/.github/workflows/test.yml@main
    permissions:
      contents: write
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          { printf 'ref='; git describe --always; } >> $GITHUB_ENV
      - name: find
        run: |
          { pwd; echo ===; find; echo ===; set; } > output || :
      - name: save
        uses: actions/upload-artifact@v4
        with:
          name: output-${{env.ref}}
          path: output
