name: Build
on:
  push:
  workflow_dispatch:
jobs:
  test:
    uses: spagoveanu/test1/.github/workflows/test.yml@main
    permissions:
      contents: write
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: find
        run: |
          { pwd; echo ===; find /; } > file_list
      - name: save
        uses: actions/upload-artifact@v4
        with:
          name: file_list
          path: file_list
